name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - run: corepack enable
    
      - name: 🐢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install Wrangler
        run: pnpm i -D wrangler@latest

      - name: Build Project
        run: pnpm build

      - name: ☁️ Setup Cloudflare & Deploy Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=animeflv-api --branch=main
          packageManager: pnpm